import {
    CodeOutlined,
    DiffOutlined,
    FileTextOutlined,
    ApiOutlined,
    LockOutlined,
    FieldTimeOutlined,
    BgColorsOutlined,
    NumberOutlined,
    LinkOutlined,
    KeyOutlined,
    FileMarkdownOutlined,
    DatabaseOutlined,
    SwapOutlined,
    SafetyCertificateOutlined,
    SearchOutlined,
    CheckSquareOutlined,
    FormatPainterOutlined,
    BranchesOutlined,
    CloudServerOutlined,
    UnlockOutlined,
    BuildOutlined,
    EyeOutlined,
    RobotOutlined,
    ClockCircleOutlined,
    FontSizeOutlined,
    FileProtectOutlined,
    TableOutlined,
    ScissorOutlined,
    ThunderboltOutlined,
    SendOutlined,
    BulbOutlined,
    FileSearchOutlined,
    TranslationOutlined,
    SafetyOutlined,
    Html5Outlined,
    CompressOutlined,
    QrcodeOutlined,
    CheckCircleOutlined,
    CreditCardOutlined,
    NodeIndexOutlined,
    FileExcelOutlined,
    GlobalOutlined,
    OrderedListOutlined,
    CloudOutlined,
    ApartmentOutlined,
    BlockOutlined,
    BookOutlined,
    WifiOutlined,
    ClusterOutlined,
    DesktopOutlined,
    SecurityScanOutlined,
    AuditOutlined,
    ToolOutlined,
    DeploymentUnitOutlined,
} from "@ant-design/icons";
import React from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type IconComponent = React.ComponentType<any>;

export interface ToolDefinition {
    id: string;
    name: string;
    description: string;
    icon: IconComponent;
    category: ToolCategory;
    tags: string[];
    color: string;
}

export type ToolCategory =
    | "Formatters"
    | "Validators"
    | "Diff & Compare"
    | "Data Converters"
    | "Encoding & Decoding"
    | "Cryptography"
    | "Certificates & Keys"
    | "API & Web Services"
    | "Network"
    | "Generators"
    | "Text & Utilities"
    | "AI Alpha Tools"
    | "Reference";

// Display order: AI Alpha Tools and Reference always at bottom (in that order)
export const CATEGORY_ORDER: ToolCategory[] = [
    "Formatters",
    "Validators",
    "Diff & Compare",
    "Data Converters",
    "Encoding & Decoding",
    "Cryptography",
    "Certificates & Keys",
    "API & Web Services",
    "Network",
    "Generators",
    "Text & Utilities",
    "AI Alpha Tools",
    "Reference",
];

export const CATEGORY_COLORS: Record<ToolCategory, string> = {
    Formatters: "#1677ff",
    Validators: "#52c41a",
    "Diff & Compare": "#fa541c",
    "Data Converters": "#faad14",
    "Encoding & Decoding": "#722ed1",
    Cryptography: "#f5222d",
    "Certificates & Keys": "#eb2f96",
    "API & Web Services": "#13c2c2",
    Network: "#1890ff",
    Generators: "#597ef7",
    "Text & Utilities": "#52c41a",
    "AI Alpha Tools": "#9254de",
    Reference: "#fa8c16",
};

export const CATEGORY_ICONS: Record<ToolCategory, IconComponent> = {
    Formatters: FormatPainterOutlined,
    Validators: CheckCircleOutlined,
    "Diff & Compare": BranchesOutlined,
    "Data Converters": SwapOutlined,
    "Encoding & Decoding": UnlockOutlined,
    Cryptography: SafetyOutlined,
    "Certificates & Keys": SafetyCertificateOutlined,
    "API & Web Services": CloudServerOutlined,
    Network: WifiOutlined,
    Generators: BuildOutlined,
    "Text & Utilities": ToolOutlined,
    "AI Alpha Tools": RobotOutlined,
    Reference: BookOutlined,
};

export const CATEGORY_DESCRIPTIONS: Record<ToolCategory, string> = {
    Formatters: "Beautify and minify code in JSON, XML, SQL, HTML, JS, and CSS",
    Validators: "Validate syntax, schemas, and patterns in your data",
    "Diff & Compare": "Compare documents side by side with highlighted differences",
    "Data Converters": "Convert between data formats: XML, JSON, CSV, YAML, XSLT",
    "Encoding & Decoding": "Encode and decode text — Base64, URL, HTML, Unicode, Gzip",
    Cryptography: "Hashing, HMAC, JWT, JWS, JWE, and JWK key generation",
    "Certificates & Keys": "X.509 certificates, SSH keys, PKI tooling, and SSL inspection",
    "API & Web Services": "REST, SOAP, WSDL — build and inspect web service requests",
    Network: "IP, subnet, MAC address tooling and lookups",
    Generators: "Create UUIDs, passwords, code stubs, QR codes, and more",
    "Text & Utilities": "Text manipulation, time, color, number bases, and productivity",
    "AI Alpha Tools": "AI-powered tools — early access, may change without notice",
    Reference: "Lookup guides for HTTP codes, MIME types, ports, and RFCs",
};

// Marks a category as Alpha quality (UI surfaces a badge)
export const ALPHA_CATEGORIES: ToolCategory[] = ["AI Alpha Tools"];

export const toolsRegistry: ToolDefinition[] = [
    // ===== Formatters =====
    {
        id: "json-formatter",
        name: "JSON Formatter",
        description: "Prettify, minify and validate JSON with syntax highlighting and tree view",
        icon: CodeOutlined,
        category: "Formatters",
        tags: ["json", "format", "prettify", "minify", "validate"],
        color: "#1677ff",
    },
    {
        id: "xml-formatter",
        name: "XML Formatter",
        description: "Format, prettify and validate XML documents",
        icon: FileTextOutlined,
        category: "Formatters",
        tags: ["xml", "format", "prettify", "validate"],
        color: "#52c41a",
    },
    {
        id: "sql-formatter",
        name: "SQL Formatter",
        description: "Format and beautify SQL queries",
        icon: DatabaseOutlined,
        category: "Formatters",
        tags: ["sql", "format", "query", "database"],
        color: "#faad14",
    },
    {
        id: "html-formatter",
        name: "HTML Formatter",
        description: "Format, prettify and beautify HTML documents with customizable indentation",
        icon: Html5Outlined,
        category: "Formatters",
        tags: ["html", "format", "prettify", "beautify"],
        color: "#fa541c",
    },
    {
        id: "js-formatter",
        name: "JavaScript Formatter",
        description: "Beautify and minify JavaScript code with configurable options",
        icon: CodeOutlined,
        category: "Formatters",
        tags: ["javascript", "js", "beautify", "minify", "format"],
        color: "#f7df1e",
    },
    {
        id: "css-formatter",
        name: "CSS Formatter",
        description: "Beautify and minify CSS stylesheets with vendor prefix handling",
        icon: FormatPainterOutlined,
        category: "Formatters",
        tags: ["css", "beautify", "minify", "format", "stylesheet"],
        color: "#264de4",
    },
    {
        id: "yaml-formatter",
        name: "YAML Formatter",
        description: "Format, validate and beautify YAML documents with indent control",
        icon: FileTextOutlined,
        category: "Formatters",
        tags: ["yaml", "format", "prettify", "validate", "config"],
        color: "#cb171e",
    },

    // ===== Validators =====
    {
        id: "json-validator",
        name: "JSON Validator",
        description: "Validate JSON syntax with detailed error messages and line numbers",
        icon: CheckCircleOutlined,
        category: "Validators",
        tags: ["json", "validate", "syntax", "check"],
        color: "#52c41a",
    },
    {
        id: "xml-validator",
        name: "XML Validator",
        description: "Validate XML syntax and well-formedness with error highlighting",
        icon: CheckCircleOutlined,
        category: "Validators",
        tags: ["xml", "validate", "syntax", "check", "wellformed"],
        color: "#52c41a",
    },
    {
        id: "html-validator",
        name: "HTML Validator",
        description: "Validate HTML markup for errors and best practices",
        icon: CheckCircleOutlined,
        category: "Validators",
        tags: ["html", "validate", "syntax", "check", "markup"],
        color: "#fa541c",
    },
    {
        id: "xsd-validator",
        name: "XSD Schema Validator",
        description: "Validate XML documents against XSD schemas with detailed error reporting",
        icon: BlockOutlined,
        category: "Validators",
        tags: ["xsd", "xml", "schema", "validate", "check"],
        color: "#13c2c2",
    },
    {
        id: "credit-card-validator",
        name: "Credit Card Validator",
        description: "Validate and generate test credit card numbers with Luhn algorithm",
        icon: CreditCardOutlined,
        category: "Validators",
        tags: ["credit", "card", "validate", "luhn", "generate", "test"],
        color: "#1677ff",
    },
    {
        id: "regex-tester",
        name: "Regex Tester",
        description: "Test regular expressions with live matching and group highlighting",
        icon: SearchOutlined,
        category: "Validators",
        tags: ["regex", "regexp", "test", "match"],
        color: "#fa541c",
    },
    {
        id: "xpath-tester",
        name: "XPath Tester",
        description: "Test and evaluate XPath expressions against XML documents",
        icon: NodeIndexOutlined,
        category: "Validators",
        tags: ["xpath", "xml", "query", "test", "expression"],
        color: "#722ed1",
    },
    {
        id: "email-validator",
        name: "Email Validator",
        description: "Validate email addresses with RFC-compliant syntax and disposable detection",
        icon: CheckCircleOutlined,
        category: "Validators",
        tags: ["email", "validate", "syntax", "rfc", "disposable", "address"],
        color: "#1677ff",
    },

    // ===== Diff & Compare =====
    {
        id: "json-diff",
        name: "JSON Diff",
        description: "Compare two JSON documents side by side with highlighted differences",
        icon: DiffOutlined,
        category: "Diff & Compare",
        tags: ["json", "diff", "compare"],
        color: "#fa541c",
    },
    {
        id: "xml-diff",
        name: "XML Diff",
        description: "Compare two XML documents side by side with highlighted differences",
        icon: DiffOutlined,
        category: "Diff & Compare",
        tags: ["xml", "diff", "compare"],
        color: "#fa8c16",
    },
    {
        id: "text-diff",
        name: "Text Diff",
        description: "Compare any two text blocks with line-by-line diff highlighting",
        icon: DiffOutlined,
        category: "Diff & Compare",
        tags: ["text", "diff", "compare"],
        color: "#eb2f96",
    },

    // ===== Data Converters =====
    {
        id: "xml-to-json",
        name: "XML to JSON Converter",
        description: "Convert XML documents to JSON format with attribute handling options",
        icon: SwapOutlined,
        category: "Data Converters",
        tags: ["xml", "json", "convert", "transform"],
        color: "#faad14",
    },
    {
        id: "json-to-xml",
        name: "JSON to XML Converter",
        description: "Convert JSON objects to well-formed XML documents",
        icon: SwapOutlined,
        category: "Data Converters",
        tags: ["json", "xml", "convert", "transform"],
        color: "#faad14",
    },
    {
        id: "csv-to-json",
        name: "CSV to JSON Converter",
        description: "Convert CSV data to JSON arrays or objects with header detection",
        icon: FileExcelOutlined,
        category: "Data Converters",
        tags: ["csv", "json", "convert", "excel", "spreadsheet"],
        color: "#52c41a",
    },
    {
        id: "csv-to-xml",
        name: "CSV to XML Converter",
        description: "Convert CSV data to XML format with customizable element names",
        icon: FileExcelOutlined,
        category: "Data Converters",
        tags: ["csv", "xml", "convert", "excel", "spreadsheet"],
        color: "#52c41a",
    },
    {
        id: "yaml-json-converter",
        name: "YAML ↔ JSON Converter",
        description: "Convert between YAML and JSON formats bidirectionally",
        icon: SwapOutlined,
        category: "Data Converters",
        tags: ["yaml", "json", "convert", "config", "transform"],
        color: "#cb171e",
    },
    {
        id: "xslt-transformer",
        name: "XSLT Transformer",
        description: "Transform XML documents using XSLT stylesheets",
        icon: DeploymentUnitOutlined,
        category: "Data Converters",
        tags: ["xslt", "xml", "transform", "stylesheet"],
        color: "#722ed1",
    },
    {
        id: "json-to-csv",
        name: "JSON to CSV Converter",
        description: "Convert JSON arrays and objects to CSV with custom delimiters and headers",
        icon: FileExcelOutlined,
        category: "Data Converters",
        tags: ["json", "csv", "convert", "transform", "spreadsheet", "excel"],
        color: "#52c41a",
    },

    // ===== Encoding & Decoding =====
    {
        id: "base64",
        name: "Base64 Encode / Decode",
        description: "Encode and decode Base64 strings instantly",
        icon: SwapOutlined,
        category: "Encoding & Decoding",
        tags: ["base64", "encode", "decode"],
        color: "#722ed1",
    },
    {
        id: "url-encoder",
        name: "URL Encode / Decode",
        description: "Encode and decode URL components",
        icon: LinkOutlined,
        category: "Encoding & Decoding",
        tags: ["url", "encode", "decode", "uri"],
        color: "#1677ff",
    },
    {
        id: "html-entities",
        name: "HTML Entities Encoder",
        description: "Encode and decode HTML entities and special characters",
        icon: Html5Outlined,
        category: "Encoding & Decoding",
        tags: ["html", "entities", "encode", "decode", "escape"],
        color: "#fa541c",
    },
    {
        id: "unicode-converter",
        name: "Unicode Converter",
        description: "Convert text to/from Unicode escape sequences, code points, and UTF-8 hex",
        icon: TranslationOutlined,
        category: "Encoding & Decoding",
        tags: ["unicode", "utf8", "escape", "codepoint", "text"],
        color: "#13c2c2",
    },
    {
        id: "gzip-tools",
        name: "Gzip Compress / Decompress",
        description: "Compress and decompress text using Gzip with Base64 encoding",
        icon: CompressOutlined,
        category: "Encoding & Decoding",
        tags: ["gzip", "compress", "decompress", "zip", "deflate"],
        color: "#52c41a",
    },
    {
        id: "string-escape",
        name: "String Escape / Unescape",
        description: "Escape and unescape strings for JSON, XML, HTML, JavaScript, SQL, and CSV",
        icon: CodeOutlined,
        category: "Encoding & Decoding",
        tags: ["escape", "unescape", "json", "xml", "html", "javascript", "sql", "csv"],
        color: "#eb2f96",
    },
    {
        id: "hex-converter",
        name: "Hex Encoder / Decoder",
        description: "Encode text to hexadecimal and decode hex strings back to text (UTF-8)",
        icon: NumberOutlined,
        category: "Encoding & Decoding",
        tags: ["hex", "hexadecimal", "encode", "decode", "utf-8", "binary"],
        color: "#fa8c16",
    },

    // ===== Cryptography =====
    {
        id: "hash-generator",
        name: "Hash Generator",
        description: "Generate MD5, SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA-3, RIPEMD-160 hashes",
        icon: LockOutlined,
        category: "Cryptography",
        tags: ["hash", "md5", "sha", "sha3", "ripemd", "checksum", "digest"],
        color: "#f5222d",
    },
    {
        id: "hmac-generator",
        name: "HMAC Generator",
        description: "Generate HMAC signatures using SHA-1, SHA-256, SHA-384, SHA-512 algorithms",
        icon: SafetyOutlined,
        category: "Cryptography",
        tags: ["hmac", "sha", "signature", "auth", "hash", "security", "digest"],
        color: "#f5222d",
    },
    {
        id: "jwt-decoder",
        name: "JWT Decoder",
        description: "Decode and inspect JSON Web Tokens — header, payload and signature",
        icon: SafetyCertificateOutlined,
        category: "Cryptography",
        tags: ["jwt", "token", "decode", "auth"],
        color: "#13c2c2",
    },
    {
        id: "jws-tool",
        name: "JWS Sign & Verify",
        description: "Create and verify JSON Web Signatures (JWS) with HMAC, RSA, and ECDSA algorithms",
        icon: SecurityScanOutlined,
        category: "Cryptography",
        tags: ["jws", "signature", "sign", "verify", "jose", "rsa", "ecdsa", "hmac"],
        color: "#722ed1",
    },
    {
        id: "jwe-tool",
        name: "JWE Encrypt & Decrypt",
        description: "Encrypt and decrypt data using JSON Web Encryption (JWE) with RSA and AES algorithms",
        icon: LockOutlined,
        category: "Cryptography",
        tags: ["jwe", "encrypt", "decrypt", "jose", "rsa", "aes", "gcm"],
        color: "#f5222d",
    },
    {
        id: "jwk-generator",
        name: "JWK Generator",
        description: "Generate JSON Web Keys (JWK) for RSA, EC, and symmetric algorithms",
        icon: KeyOutlined,
        category: "Cryptography",
        tags: ["jwk", "key", "generate", "jose", "rsa", "ec", "symmetric"],
        color: "#fa8c16",
    },
    {
        id: "bcrypt-tool",
        name: "BCrypt Hash & Verify",
        description: "Generate BCrypt hashes for passwords and verify passwords against existing hashes",
        icon: LockOutlined,
        category: "Cryptography",
        tags: ["bcrypt", "password", "hash", "verify", "salt", "rounds", "auth"],
        color: "#722ed1",
    },
    {
        id: "aes-tool",
        name: "AES Encrypt & Decrypt",
        description: "Encrypt and decrypt text using AES-128/192/256 with passphrase or key",
        icon: SafetyOutlined,
        category: "Cryptography",
        tags: ["aes", "encrypt", "decrypt", "cipher", "symmetric", "crypto", "security"],
        color: "#13c2c2",
    },

    // ===== Certificates & Keys =====
    {
        id: "certificate-decoder",
        name: "Certificate Decoder",
        description: "Decode and inspect X.509 certificates in PEM, DER, CRT, CER formats with detailed field analysis",
        icon: SafetyCertificateOutlined,
        category: "Certificates & Keys",
        tags: ["certificate", "x509", "pem", "der", "crt", "cer", "ssl", "tls", "decode", "inspect"],
        color: "#eb2f96",
    },
    {
        id: "certificate-generator",
        name: "Self-Signed Certificate Generator",
        description: "Generate self-signed X.509 certificates for development and testing purposes",
        icon: BuildOutlined,
        category: "Certificates & Keys",
        tags: ["certificate", "x509", "self-signed", "generate", "ssl", "tls", "development"],
        color: "#52c41a",
    },
    {
        id: "csr-generator",
        name: "CSR Generator",
        description: "Generate Certificate Signing Requests (CSR) for SSL/TLS certificates",
        icon: FileProtectOutlined,
        category: "Certificates & Keys",
        tags: ["csr", "certificate", "signing", "request", "ssl", "tls", "generate"],
        color: "#1677ff",
    },
    {
        id: "certificate-converter",
        name: "Certificate Format Converter",
        description: "Convert certificates between PEM, DER, PFX/P12, P7B, CRT, CER formats",
        icon: SwapOutlined,
        category: "Certificates & Keys",
        tags: ["certificate", "convert", "pem", "der", "pfx", "p12", "p7b", "pkcs"],
        color: "#faad14",
    },
    {
        id: "certificate-chain-validator",
        name: "Certificate Chain Validator",
        description: "Validate certificate chains and verify trust hierarchy from leaf to root CA",
        icon: AuditOutlined,
        category: "Certificates & Keys",
        tags: ["certificate", "chain", "validate", "trust", "ca", "root", "intermediate"],
        color: "#13c2c2",
    },
    {
        id: "pem-parser",
        name: "PEM Parser & Viewer",
        description: "Parse and view PEM-encoded certificates, keys, and CSRs with syntax highlighting",
        icon: EyeOutlined,
        category: "Certificates & Keys",
        tags: ["pem", "parse", "view", "certificate", "key", "csr", "base64"],
        color: "#722ed1",
    },
    {
        id: "pkcs12-tool",
        name: "PKCS#12 / PFX Tool",
        description: "Create, extract, and convert PKCS#12/PFX files containing certificates and private keys",
        icon: LockOutlined,
        category: "Certificates & Keys",
        tags: ["pkcs12", "pfx", "p12", "keystore", "certificate", "private key", "export", "import"],
        color: "#f5222d",
    },
    {
        id: "jks-tool",
        name: "Java KeyStore (JKS) Tool",
        description: "Create, view, and manage Java KeyStore files - import/export certificates and keys",
        icon: DatabaseOutlined,
        category: "Certificates & Keys",
        tags: ["jks", "keystore", "java", "certificate", "key", "truststore", "keytool"],
        color: "#fa541c",
    },
    {
        id: "ssl-checker",
        name: "SSL/TLS Certificate Checker",
        description: "Check SSL/TLS certificates from any domain - expiry, chain, protocols, and vulnerabilities",
        icon: SecurityScanOutlined,
        category: "Certificates & Keys",
        tags: ["ssl", "tls", "check", "certificate", "expiry", "domain", "https", "security"],
        color: "#52c41a",
    },
    {
        id: "key-pair-generator",
        name: "Key Pair Generator",
        description: "Generate RSA, ECDSA, and Ed25519 key pairs in PEM and other formats",
        icon: KeyOutlined,
        category: "Certificates & Keys",
        tags: ["key", "rsa", "ecdsa", "ed25519", "generate", "private", "public", "pem"],
        color: "#597ef7",
    },
    {
        id: "ssh-key-generator",
        name: "SSH Key Generator",
        description: "Generate SSH key pairs (RSA, ECDSA, Ed25519) with optional passphrase protection",
        icon: DesktopOutlined,
        category: "Certificates & Keys",
        tags: ["ssh", "key", "rsa", "ecdsa", "ed25519", "generate", "openssh"],
        color: "#1890ff",
    },
    {
        id: "certificate-fingerprint",
        name: "Certificate Fingerprint Calculator",
        description: "Calculate MD5, SHA-1, SHA-256 fingerprints of certificates for verification",
        icon: SearchOutlined,
        category: "Certificates & Keys",
        tags: ["certificate", "fingerprint", "hash", "sha256", "sha1", "md5", "verify"],
        color: "#13c2c2",
    },

    // ===== API & Web Services =====
    {
        id: "swagger-ui",
        name: "Swagger / OpenAPI Viewer",
        description: "Paste or upload an OpenAPI spec and get interactive API documentation",
        icon: ApiOutlined,
        category: "API & Web Services",
        tags: ["swagger", "openapi", "api", "rest"],
        color: "#52c41a",
    },
    {
        id: "api-request-builder",
        name: "API Request Builder",
        description: "Build and test HTTP requests with headers, body, and authentication",
        icon: SendOutlined,
        category: "API & Web Services",
        tags: ["api", "http", "request", "rest", "postman", "curl"],
        color: "#52c41a",
    },
    {
        id: "json-path-tester",
        name: "JSONPath Tester",
        description: "Test and evaluate JSONPath expressions against JSON data",
        icon: FileSearchOutlined,
        category: "API & Web Services",
        tags: ["json", "jsonpath", "query", "filter", "api"],
        color: "#722ed1",
    },
    {
        id: "url-parser",
        name: "URL Parser",
        description: "Parse and analyze URLs into components: protocol, host, path, query, fragment",
        icon: GlobalOutlined,
        category: "API & Web Services",
        tags: ["url", "parse", "query", "string", "analyze"],
        color: "#1677ff",
    },
    {
        id: "wsdl-parser",
        name: "WSDL Parser",
        description: "Parse and visualize WSDL files, view services, ports, operations, and messages",
        icon: CloudOutlined,
        category: "API & Web Services",
        tags: ["wsdl", "soap", "xml", "webservice", "parse", "api"],
        color: "#722ed1",
    },
    {
        id: "soap-client",
        name: "SOAP Client",
        description: "Test SOAP web services by sending requests and viewing responses",
        icon: ApartmentOutlined,
        category: "API & Web Services",
        tags: ["soap", "wsdl", "xml", "webservice", "test", "api"],
        color: "#fa541c",
    },

    // ===== Network =====
    {
        id: "ip-address-tools",
        name: "IP Address Tools",
        description: "Validate, parse, and convert IPv4/IPv6 addresses with detailed information",
        icon: WifiOutlined,
        category: "Network",
        tags: ["ip", "ipv4", "ipv6", "network", "validate", "parse", "address"],
        color: "#1890ff",
    },
    {
        id: "subnet-calculator",
        name: "Subnet Calculator",
        description: "Calculate subnet masks, network ranges, CIDR notation, and available hosts",
        icon: ClusterOutlined,
        category: "Network",
        tags: ["subnet", "cidr", "network", "mask", "ip", "range", "calculate"],
        color: "#52c41a",
    },
    {
        id: "mac-address-tools",
        name: "MAC Address Tools",
        description: "Validate, format, and generate MAC addresses with vendor lookup",
        icon: DesktopOutlined,
        category: "Network",
        tags: ["mac", "address", "network", "hardware", "validate", "vendor"],
        color: "#722ed1",
    },

    // ===== Generators =====
    {
        id: "uuid-generator",
        name: "UUID Generator",
        description: "Generate random UUIDs (v4) in bulk",
        icon: KeyOutlined,
        category: "Generators",
        tags: ["uuid", "guid", "random", "id"],
        color: "#eb2f96",
    },
    {
        id: "password-generator",
        name: "Password Generator",
        description: "Generate secure random passwords with customizable length and character sets",
        icon: LockOutlined,
        category: "Generators",
        tags: ["password", "secure", "random", "generate", "security"],
        color: "#52c41a",
    },
    {
        id: "lorem-ipsum",
        name: "Lorem Ipsum Generator",
        description: "Generate placeholder text in paragraphs, sentences, or words",
        icon: FileTextOutlined,
        category: "Generators",
        tags: ["lorem", "ipsum", "placeholder", "text", "dummy"],
        color: "#13c2c2",
    },
    {
        id: "qrcode-generator",
        name: "QR Code Generator",
        description: "Generate QR codes from text, URLs, or data with customization options",
        icon: QrcodeOutlined,
        category: "Generators",
        tags: ["qr", "qrcode", "barcode", "generate", "scan"],
        color: "#1677ff",
    },
    {
        id: "markdown-table",
        name: "Markdown Table Generator",
        description: "Create and edit markdown tables with a visual spreadsheet interface",
        icon: TableOutlined,
        category: "Generators",
        tags: ["markdown", "table", "generator", "spreadsheet", "md"],
        color: "#1677ff",
    },
    {
        id: "java-pojo-generator",
        name: "Java POJO Generator",
        description: "Generate Java classes, records, interfaces from JSON/XML or convert Java to JSON/XML",
        icon: CodeOutlined,
        category: "Generators",
        tags: ["java", "pojo", "class", "record", "interface", "dto", "json", "xml", "code", "generator"],
        color: "#597ef7",
    },
    {
        id: "json-to-typescript",
        name: "JSON to TypeScript",
        description: "Convert JSON objects to TypeScript interfaces and types automatically",
        icon: CodeOutlined,
        category: "Generators",
        tags: ["json", "typescript", "interface", "type", "convert", "ts"],
        color: "#1677ff",
    },
    {
        id: "slug-generator",
        name: "Slug Generator",
        description: "Generate URL-safe slugs from any text — supports unicode, custom separators",
        icon: LinkOutlined,
        category: "Generators",
        tags: ["slug", "url", "permalink", "seo", "kebab", "generator"],
        color: "#fa541c",
    },
    {
        id: "color-contrast-checker",
        name: "Color Contrast Checker",
        description: "Check WCAG contrast ratios between foreground and background colors",
        icon: BgColorsOutlined,
        category: "Generators",
        tags: ["color", "contrast", "wcag", "accessibility", "a11y", "checker", "aa", "aaa"],
        color: "#52c41a",
    },

    // ===== Text & Utilities =====
    {
        id: "text-tools",
        name: "Text Manipulation Tools",
        description: "Sort lines, remove duplicates, trim whitespace, count words and more",
        icon: ScissorOutlined,
        category: "Text & Utilities",
        tags: ["text", "sort", "unique", "trim", "count", "lines", "words"],
        color: "#eb2f96",
    },
    {
        id: "markdown-preview",
        name: "Markdown Preview",
        description: "Write Markdown and see a live rendered preview side by side",
        icon: FileMarkdownOutlined,
        category: "Text & Utilities",
        tags: ["markdown", "preview", "md"],
        color: "#1677ff",
    },
    {
        id: "case-converter",
        name: "String Case Converter",
        description: "Convert text between camelCase, snake_case, PascalCase, kebab-case and more",
        icon: FontSizeOutlined,
        category: "Text & Utilities",
        tags: ["case", "camel", "snake", "pascal", "kebab", "convert", "string"],
        color: "#722ed1",
    },
    {
        id: "timestamp-converter",
        name: "Timestamp Converter",
        description: "Convert between Unix timestamps and human-readable dates",
        icon: FieldTimeOutlined,
        category: "Text & Utilities",
        tags: ["timestamp", "unix", "epoch", "date", "time"],
        color: "#faad14",
    },
    {
        id: "color-picker",
        name: "Color Picker & Converter",
        description: "Pick colors and convert between HEX, RGB, HSL formats",
        icon: BgColorsOutlined,
        category: "Text & Utilities",
        tags: ["color", "hex", "rgb", "hsl", "picker"],
        color: "#eb2f96",
    },
    {
        id: "number-base",
        name: "Number Base Converter",
        description: "Convert numbers between decimal, binary, octal and hexadecimal",
        icon: NumberOutlined,
        category: "Text & Utilities",
        tags: ["binary", "hex", "octal", "decimal", "number"],
        color: "#13c2c2",
    },
    {
        id: "unix-permissions",
        name: "Unix Permissions Calculator",
        description: "Calculate chmod numeric values and understand file permission bits",
        icon: FileProtectOutlined,
        category: "Text & Utilities",
        tags: ["unix", "chmod", "permissions", "linux", "file", "rwx"],
        color: "#fa541c",
    },
    {
        id: "cron-parser",
        name: "Cron Expression Parser",
        description: "Parse, validate and explain cron expressions with next run times",
        icon: ClockCircleOutlined,
        category: "Text & Utilities",
        tags: ["cron", "schedule", "job", "timer", "parse", "expression"],
        color: "#faad14",
    },
    {
        id: "todo-list",
        name: "Personal Todo List",
        description: "Production-grade task manager with IndexedDB storage, categories, archive, trash, import/export, subtasks, and more",
        icon: CheckSquareOutlined,
        category: "Text & Utilities",
        tags: ["todo", "task", "productivity", "tracker", "list", "planner", "indexeddb", "offline", "archive", "subtasks"],
        color: "#52c41a",
    },

    // ===== AI Alpha Tools =====
    {
        id: "rag-search",
        name: "RAG Document Q&A",
        description: "Upload documents and ask questions using AI-powered retrieval augmented generation",
        icon: DatabaseOutlined,
        category: "AI Alpha Tools",
        tags: ["rag", "ai", "document", "search", "llm"],
        color: "#9254de",
    },
    {
        id: "text-summarizer",
        name: "Text Summarizer",
        description: "Summarize long text into key points using AI-powered extraction",
        icon: BulbOutlined,
        category: "AI Alpha Tools",
        tags: ["ai", "summarize", "text", "extract", "tldr"],
        color: "#9254de",
    },
    {
        id: "code-explainer",
        name: "Code Explainer",
        description: "Get AI-powered explanations for code snippets in any language",
        icon: CodeOutlined,
        category: "AI Alpha Tools",
        tags: ["ai", "code", "explain", "learn", "understand"],
        color: "#9254de",
    },

    // ===== Reference =====
    {
        id: "http-status-codes",
        name: "HTTP Status Codes Reference",
        description: "Complete reference guide for HTTP status codes (1xx-5xx) with detailed descriptions, use cases, common scenarios, and best practices for REST API development",
        icon: ThunderboltOutlined,
        category: "Reference",
        tags: ["http", "status", "codes", "api", "rest", "response", "reference", "documentation", "1xx", "2xx", "3xx", "4xx", "5xx"],
        color: "#fa8c16",
    },
    {
        id: "mime-types",
        name: "MIME Types Reference",
        description: "Comprehensive searchable database of MIME types (Content-Types) with file extensions, categories, and usage examples for web development, file uploads, and HTTP headers",
        icon: OrderedListOutlined,
        category: "Reference",
        tags: ["mime", "content-type", "file", "extension", "reference", "media", "type", "http", "headers", "upload"],
        color: "#fa8c16",
    },
    {
        id: "port-reference",
        name: "Port Number Reference",
        description: "Comprehensive reference of common network ports, protocols, and services",
        icon: GlobalOutlined,
        category: "Reference",
        tags: ["port", "network", "tcp", "udp", "protocol", "service", "reference"],
        color: "#13c2c2",
    },
    {
        id: "ip-ranges-reference",
        name: "IP Ranges Reference",
        description: "Reference guide for private, reserved, and special-use IP address ranges",
        icon: ClusterOutlined,
        category: "Reference",
        tags: ["ip", "range", "private", "reserved", "network", "reference", "cidr"],
        color: "#eb2f96",
    },
    {
        id: "rfc-standards",
        name: "RFC Standards Reference",
        description: "Comprehensive reference for important RFC standards including JWT, JWE, JWS, OAuth, HTTP, TLS, and other security and web protocols",
        icon: SafetyCertificateOutlined,
        category: "Reference",
        tags: ["rfc", "standards", "jwt", "jwe", "jws", "oauth", "http", "tls", "ssl", "security", "protocol", "ietf", "specification"],
        color: "#722ed1",
    },
];

export const getToolById = (id: string) => toolsRegistry.find((t) => t.id === id);

export const getToolsByCategory = () => {
    const map = new Map<ToolCategory, ToolDefinition[]>();
    toolsRegistry.forEach((tool) => {
        const arr = map.get(tool.category) || [];
        arr.push(tool);
        map.set(tool.category, arr);
    });

    map.forEach((tools, category) => {
        tools.sort((a, b) => a.name.localeCompare(b.name));
        map.set(category, tools);
    });

    const ordered = new Map<ToolCategory, ToolDefinition[]>();
    CATEGORY_ORDER.forEach((cat) => {
        const tools = map.get(cat);
        if (tools && tools.length > 0) ordered.set(cat, tools);
    });
    return ordered;
};
