/**
 * Edge-safe `toolId → category` for `proxy.ts` (no React / Ant icons).
 * Keep in sync with `tools-registry.ts` and any standalone redirect routes (`ssl-checker`, etc.).
 */
export const TOOL_ID_TO_CATEGORY = {
  "json-formatter": "Formatters",
  "xml-formatter": "Formatters",
  "sql-formatter": "Formatters",
  "html-formatter": "Formatters",
  "js-formatter": "Formatters",
  "css-formatter": "Formatters",
  "yaml-formatter": "Formatters",
  "json-validator": "Validators",
  "xml-validator": "Validators",
  "html-validator": "Validators",
  "xsd-validator": "Validators",
  "credit-card-validator": "Validators",
  "regex-tester": "Validators",
  "xpath-tester": "Validators",
  "email-validator": "Validators",
  "json-diff": "Diff & Compare",
  "xml-diff": "Diff & Compare",
  "text-diff": "Diff & Compare",
  "xml-to-json": "Data Converters",
  "json-to-xml": "Data Converters",
  "csv-to-json": "Data Converters",
  "csv-to-xml": "Data Converters",
  "yaml-json-converter": "Data Converters",
  "xslt-transformer": "Data Converters",
  "json-to-csv": "Data Converters",
  "base64": "Encoding & Decoding",
  "url-encoder": "Encoding & Decoding",
  "html-entities": "Encoding & Decoding",
  "unicode-converter": "Encoding & Decoding",
  "gzip-tools": "Encoding & Decoding",
  "string-escape": "Encoding & Decoding",
  "hex-converter": "Encoding & Decoding",
  "hash-generator": "Cryptography",
  "hmac-generator": "Cryptography",
  "jwt-decoder": "Cryptography",
  "jws-tool": "Cryptography",
  "jwe-tool": "Cryptography",
  "jwk-generator": "Cryptography",
  "bcrypt-tool": "Cryptography",
  "aes-tool": "Cryptography",
  "certificate-inspector": "Certificates & Keys",
  "ssl-checker": "Certificates & Keys",
  "certificate-converter": "Certificates & Keys",
  "certificate-decoder": "Certificates & Keys",
  "certificate-fingerprint": "Certificates & Keys",
  "pem-parser": "Certificates & Keys",
  "csr-generator": "Certificates & Keys",
  "certificate-chain-validator": "Certificates & Keys",
  "certificate-generator": "Certificates & Keys",
  "pkcs12-tool": "Certificates & Keys",
  "jks-tool": "Certificates & Keys",
  "key-pair-generator": "Certificates & Keys",
  "ssh-key-generator": "Certificates & Keys",
  "swagger-ui": "API & Web Services",
  "api-request-builder": "API & Web Services",
  "json-path-tester": "API & Web Services",
  "url-parser": "API & Web Services",
  "wsdl-parser": "API & Web Services",
  "soap-client": "API & Web Services",
  "mcp-inspector": "API & Web Services",
  "a2a-inspector": "API & Web Services",
  "ip-address-tools": "Network",
  "subnet-calculator": "Network",
  "mac-address-tools": "Network",
  "uuid-generator": "Generators",
  "password-generator": "Generators",
  "lorem-ipsum": "Generators",
  "qrcode-generator": "Generators",
  "markdown-table": "Generators",
  "java-pojo-generator": "Generators",
  "json-to-typescript": "Generators",
  "slug-generator": "Generators",
  "color-contrast-checker": "Generators",
  "text-tools": "Text & Utilities",
  "markdown-preview": "Text & Utilities",
  "case-converter": "Text & Utilities",
  "timestamp-converter": "Text & Utilities",
  "color-picker": "Text & Utilities",
  "number-base": "Text & Utilities",
  "unix-permissions": "Text & Utilities",
  "cron-parser": "Text & Utilities",
  "todo-list": "Text & Utilities",
  "timer": "Text & Utilities",
  "stopwatch": "Text & Utilities",
  "rag-search": "AI Alpha Tools",
  "text-summarizer": "AI Alpha Tools",
  "code-explainer": "AI Alpha Tools",
  "http-status-codes": "Reference",
  "mime-types": "Reference",
  "port-reference": "Reference",
  "ip-ranges-reference": "Reference",
  "rfc-standards": "Reference",
} as const;
export type ToolIdForRoute = keyof typeof TOOL_ID_TO_CATEGORY;
